Traceback (most recent call last):
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\main.py", line 15, in <module>
    run(config["experiment"])
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\runner.py", line 59, in run
    tm = RNNTrainingModule1(model, optimizer, config)
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\training\training_rnn_ext1.py", line 6, in __init__
    super().__init__(model, optimizer, params)
  File "C:\Users\tobia\Documents\GitHub\RNN_Tobia_Simmler\src\training\training_abstractbaseclass.py", line 23, in __init__
    self.make_gradients_plot = config["options"]["plot_gradients"]
KeyError: 'plot_gradients'